---
title: Resume
author: Alan Derbyshire
date: '2017-06-28'
slug: resume
categories:
  - cv
tags:
  - Urban planning
  - Spatial visualisation
draft: yes
---
### Higher Education
- 2010 - 2016,   Manchester Metropolitan University 
- 1985 – 1988,   University of Illinois at Champaign Urbana 
- 1981 – 1984,   Stourbridge College of Art 

### Qualifications
- 2016,	Doctor of Philosophy – Architectural and Urban Resilience; Manchester School of Architecture 
- 1988,	Master of Fine Arts - Sculpture; University of Illinois at Champaign Urbana
- 1984,	Bachelor of Arts (Hons) First Class – 3D Design; Stourbridge College of Art

### Current Position	
_DataTeka_ – Co founder, main area of focus – the visualization of resilient architecture and urban development through data mining and visual representation.

### Previous Post			
1991 – 2014, Senior Lecturer in Design, University of Central Lancashire

##### Duties included:	
- Delivery of Contemporary Contextual Design modules across all of the disciplines within the School of Art and Design;

- Member of cross-school Sustainability Research steering forum; 

- Course Leadership; 

- Module Leader – Sustainable Design, Interior Design,  Design Futures, Creative thinking, Furniture Design, Visual Communication;

- Teaching of the schools’ existing undergraduate and postgraduate courses;

- Personal tutoring to undergraduate and post graduate program students;

- Tutoring of undergraduate placement visits;

- Engaging in peer monitoring activities; 

- Writing, developing and delivering new courses and modules;

-	Developing and delivering data visualisation training for university’s staff members;

-	Directing and developing a personal research programme leading to publications in international peer-reviewed academic journals and to other appropriate forms of research output;

-	Participating in research teams and other collaborative research initiatives; 

-	Liaising with the external bodies and institutions in collaborative research work;

-	Presenting and negotiating project proposals;

- Leading in the writing of grants proposals;

- Participating in the Department’s, School’s and University’s various outreach activities including Open Days etc.

### Research and Practice Expertise
- Excellent knowledge (published papers) of spatial theory and philosophical underpinning of space and place oriented objectives.

- Excellent understanding  (research awards) of concepts of sustainability and resilience within architecture and urban landscapes.

- High quality (live projects) practical and theoretical grounding in external and internal spatial remodeling – domestic, commercial and landscape.

- High level (commissioned installations) of craft and sculpture projects demonstrating symbiotic relationships between materials, light and spatial structuring.

- Excellent knowledge (published papers/live projects) of ecological relationships with spatial and formal characteristics within architecture and environment.

- High level (published papers/teaching delivery) of experience and knowledge of design theory and practice, communication strategies, outcome dissemination.

- Excellent record (institutional and student feedback mechanisms) in knowledge transfer, funding acquisition and research based teaching.

### External Roles	
- Associate Editor: _International Journal of Design Principles and Practice_; Duties included peer reviewing papers, submitting reports.

- Associate Editor: _International Journal of International Journal of Environmental, Cultural, Economic and Social Sustainability_; Duties included peer-reviewing papers, submitting reports

- Associate Editor: _Proceedings of the ICE – Urban Design and Planning_; Liaising with scientific committee, reviewing articles, submitting reports. 

- Reviewer: _Open Urban Studies and Demography Journal_; article reviews and reports.

- Consultant: _Urban Green Spaces – Healthy Cities U.K_; Delivering presentations to environmental stakeholders and policy makers. Designing and delivering webinars to actors in the field of urban renewal, developing strategies for effective ‘greening’ of brown field sites.

### Previous Appointments		

1995 – 1997 _Part-time Lecturer in Design, Stockport College._ Delivery of 3D modules to Foundation level students.

1993 – 1995	_Part-time Lecturer in Design,  Loughborough University._ Delivery of 3D disciplines including sculpture, interior, furniture and craft to foundation and post graduate students.

1991 – 1993	_Associate Lecturer in Design, Southport College._ Delivery of all 3D disciplines to foundation students.

### Professional Activities: 	
- _Dennis Oppenheim Sculpture, N.Y.C._ 1989 – Assistant.
Responsibilities included: making artist’s work from drawings, building and installation of  ‘installation’ works, working with team members on large scale projects.

- _Jeffrey Fuller Gallery, Philadelphia 1990_ – Exhibition Coordinator.
Responsibilities included: organizing exhibition space, hanging all works, organizing private views, 

- _Merseyside Arts, Artist in Residence, 1990 – 1991_
Duties included: building a glass studio, making work for exhibition, delivery of workshops and seminars, interfacing with local and national press and media, disseminating outcomes.

### Projects	
- Sustainable Urban Landscapes Design Consultant: 2005 – Present.
Principal activities involve client liaison, design presentation and pitches, commissioning of contractors, quality control and monitoring of outcomes.

- Project Manager, Landscapes – Woolyback Productions 2004 – 2005.
Project involved restructuring the external spaces of the office of a Film and TV production company. Responsibilities included pitching concepts and designs to the partners, commissioning contractors,  monitoring work done, quality control.

- Project Manager, ‘Johnny House’ – Johnny Vegas 2002 – 2004.
	A significant scale project involving the total restructuring of the property, spatial reconfiguration of interior, design and build of personal studio, design of furniture, interiors and installation of commissioned artworks. Responsibilities included liaising with planning departments and structural engineers, monitoring of contractors work, commissioning builders, provide reports to the client, sign off all work on completion.
	
### Awards	
- _Sabbatical Award_, University of Central Lancashire, Seconded to Montenegro – Boka Kotorska – Vernacular structures and sustainability, 2013.

- _Reed and Mallik  Medal_, Awarded by The Institute of Civil Engineers for best published paper in their journals on the subject of Urban Design: Sustainable urban habitats: design intentions to practical implementation., 2012.

### Recent Publications

#### Book Chapter:

Derbyshire, Alan, (2015) _The Components of Viable Eco-Diverse Landscapes_. In D. Humphries, S, Stober, eds. Transitions to Sustainability: Theoretical Debates for a Changing Planet. Common Ground Publishing

#### Peer Reviewed Journal Articles:

Derbyshire, Alan (2016) _Regions in Transition: The Shift From Distinctive to Bland, a Lesson for Built Environment Stakeholders_. Journal of Urban Design and Planning, Volume 169, Issue 6.

Derbyshire, Alan and Kecojevic, Tatjana (2014) _Boka Kotorska: A Vernacular Response to Sustainable Urban Environments_. Journal of Architecture and Urbanism,  Volume **38**(2): 148–160

Derbyshire, Alan (2011) _Sustainable urban habitats: Design intentions to practical implementation_. Proceedings of the ICE - Urban Design and Planning, 164 (1). pp. 19-28. ISSN 1755-0793 

Derbyshire, Alan (2010) _Sustainable Urban Habitats: The Contributory Components of Viable Eco-Diverse Landscapes_. International Journal of Environmental, Cultural, Economic and Social Sustainability , **6**(2). pp. 265-276. ISSN ISSN: 1832-2077

Derbyshire, Alan (2010) _Do Architects Draw Trees? – Shifting the Perception of Urban Landscape Form_. In: Sustainable Architecture and Urban Development. CSAAR Transactions on the Built Environment, 2 . CSAAR Press, Jordan, pp. 67-79. ISBN 978-9957-540-01-2

Derbyshire, Alan (2009) _Modular sustainability within the landscape_. Design Principles and Practices: An International Journal, **3**(2). pp. 227-248. ISSN 1833-1874

#### Forthcoming:

Derbyshire, Alan, Tatjana Kecojevic (2017). _Data Landscapes: a pragmatic and philosophical visualisation of the  sustainable urban landscape_. Submitted – Journal of Architectural and Planning Research.

Derbyshire, Alan, (2017) _Cultural Identity in Ecological Context: Urban Development of a Region in Transition_.  Submitted – The journal Landscape and Urban Planning

### Conference Papers – Peer Reviewed

- Derbyshire, Alan, Tatjana Kecojevic (2016).  _Data Landscapes: a pragmatic and philosophical visualisation of the  sustainable urban landscape_. R Users 2016 Conference, Stanford University, 27th – 30th June, 2016.

- Derbyshire, Alan (2015) _Vernacular form of the Boka Kotorska: Memory, Tradition and Inherent Resilient Thinking_. AR 2015 Architecture and Resilience on a Human Scale, University of Sheffield, September 2015.

- Derbyshire, Alan, Tatjana, Kecojevic (2012) _The Evolution of the Boka Kotorska as a Sustainable Ecological Entity_. In: Proceedings IFKAD-KCWS 2012 - Knowledge, Innovation and Sustainability: integrating micro and macro perspectives. IFKAD-KCWS , Matera, Italy, 

- Derbyshire, Alan (2010) _Greening the Grey. The Design Outlook for Ecological Urban Sustainability_. Conference on Universal Design, Hamamatsu, Japan October 2010

- Derbyshire, Alan (2010) _Do Architects Draw Trees? – Shifting the Perception of Urban Landscape Form_. Conference of Sustainable Architecture and Urban Development, Amman Jordan July 2010.

- Derbyshire, Alan (2009) _Sustainable Urban Habitats: A study of the threads that connect design intentions to practical implementation_. Urban Design Australia, Queensland Australia, September 2009.
