baseurl = "https://alanderbyshire.github.io/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Alexis Tacnet"
title = "Alan Derbyshire"
disqusshortname = "alan-derbyshire-github-io"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Alan's website"
copyright = "Copyright © 2017 Alan Derbyshire"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/me-image.jpg"
faviconfile = "img/me-image.jpg"
highlightjs = true
progressively = true
share = true
latestpostcount = 5
github = "AlanDerbyshire"
email = "akderbyshire.ad@gmailcom.com"
linkedin = "john-example-aa80ue8è"
twitter = "DataTeka"
#facebook = "facebook_id"
social_banner = "img/me-image.jpg"
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName"

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
